version: '3.7'
services:
  mysql:
    platform: linux/x86_64
    container_name: mysql
    ports:
      - '3306:3306'
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_DATABASE=deploymanagement
      - MYSQL_ROOT_PASSWORD=rootpassword
    volumes:
      - mysql:/var/lib/mysql
  api:
    platform: linux/x86_64
    links:
      - mysql
    depends_on:
      - mysql
    restart: always
    container_name: deploy-management-api
    build: 
      context: .
      dockerfile: Dockerfile
    ports: 
      - '3000:3000'
      - '9222:9222'
    volumes:
      - ./:/app
      - ./prisma:/app/prisma
      - /app/node_modules
    command: npm run debug
    env_file:
      - ./local.env
volumes:
  mysql: